version: "3.4"

services:
  isseven:
    build:
      context: ./
      dockerfile: Dockerfile
      target: web
    environment:
      PORT: "8001"
      HOST: "0.0.0.0"
    ports:
    - "8001:8001"
  test:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev